<?php
/**
 * @copyright Copyright © 2020 Magepow. All rights reserved.
 * @author    Magepow
 * @category Magepow
 * @copyright Copyright (c) 2014 Magepow (<https://www.magepow.com>)
 * @license <https://www.magepow.com/license-agreement.html>
 * @Author: magepow<support@magepow.com>
 * @github: <https://github.com/magepow>
 */
/** @var Magento\Backend\Block\Template $block */

/** @var Magepow\CheckoutCustomForm\Model\Data\CustomFields $customFields */
$customFields = $block->getOrderCustomFields();
?>
<?php if($customFields): ?>
    <?php if($customFields->getImeiTime() || $customFields->getCheckboxBankTranfer() || $customFields->getBankNameOnAccount() || $customFields->getBankAccountNumber() || $customFields->getBankAccountShortCode()): ?>
    <?php 
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $orderId  = $this->getRequest()->getParam('order_id');
        $orderRepository = $objectManager->create('Magento\Sales\Api\OrderRepositoryInterface')->get($orderId);
        $checkPayment = $orderRepository->getPayment()->getData('method');
    ?>
    <div class="admin__page-section-content custom-magepow-bank" style="margin-top: 20px;">
        <div class="admin__page-section-item-title">
            <span class="title"><?php /* @escapeNotVerified */ echo __('Billing Information') ?></span>
        </div>
        <div class="order-information">
            <?php if($customFields->getImeiTime()): ?>
                <div class="box">
                    <label class="box-title"><span><?php /* @escapeNotVerified */ echo __('Imei:') ?></span></label>
                    <div class="box-content">
                        <?php echo $this->escapeHtml($customFields->getImeiTime()); ?>
                    </div>
                </div>
                <br>
            <?php  endif; ?>
            <?php if($checkPayment == 'checkmo'): ?>
                <?php if($customFields->getCheckboxBankTranfer()): ?>
                    <div class="box">
                        <label class="box-title"><span><?php /* @escapeNotVerified */ echo __('PayPal Email:') ?></span></label>
                        <div class="box-content">
                            <?php echo $this->escapeHtml($customFields->getCheckboxBankTranfer()); ?>
                        </div>
                    </div><br>
                <?php  endif; ?>
            <?php elseif($checkPayment == 'banktransfer'): ?>
                <?php if($customFields->getBankNameOnAccount()): ?>
                    <div class="box">
                        <label class="box-title"><span><?php /* @escapeNotVerified */ echo __('Name On Account:') ?></span></label>
                        <div class="box-content">
                            <?php echo $this->escapeHtml($customFields->getBankNameOnAccount()); ?>
                        </div>
                    </div><br>
                <?php  endif; ?>
                <?php if($customFields->getBankAccountNumber()): ?>
                    <div class="box">
                        <label class="box-title"><span><?php /* @escapeNotVerified */ echo __('Account Number:') ?></span></label>
                        <div class="box-content">
                            <?php echo $this->escapeHtml($customFields->getBankAccountNumber()); ?>
                        </div>
                    </div><br>
                <?php  endif; ?>
                <?php if($customFields->getBankAccountShortCode()): ?>
                    <div class="box">
                        <label class="box-title"><span><?php /* @escapeNotVerified */ echo __('Account Short Code:') ?></span></label>
                        <div class="box-content">
                            <?php echo $this->escapeHtml($customFields->getBankAccountShortCode()); ?>
                        </div>
                    </div><br>
                <?php  endif; ?>
            <?php  endif; ?>
        </div>
    </div>
    <?php echo $customFields->getCheckoutCollectionSchedule() ?>
    <div class="admin__page-section-content custom-magepow-shipping-method" style="margin-top: 20px;">
        <div class="order-information">
            <?php if($customFields->getCheckoutCollectionSchedule() == 'value_1'): ?>
                <div class="box">
                    <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Collection Today') ?></span></strong>
                </div><br>
                <?php if($customFields->getCheckoutCollectionTime()): ?>
                    <div class="box">
                        <label class="box-title"><span><?php /* @escapeNotVerified */ echo __('Collection Time:') ?></span></label>
                        <div class="box-content">
                            <?php// echo $this->escapeHtml($customFields->getCheckoutCollectionTime()); ?>
                        </div>
                    </div><br>
                <?php  endif; ?>
            <?php elseif($customFields->getCheckoutCollectionSchedule() == 'value_2'): ?>
                <div class="box">
                    <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Schedule for Later') ?></span></strong>
                </div><br>
                <?php if($customFields->getCheckoutDeliveryDate()): ?>
                    <div class="box">
                        <label class="box-title"><span><?php /* @escapeNotVerified */ echo __('Delivery Date:') ?></span></label>
                        <div class="box-content">
                            <?php echo $this->escapeHtml($customFields->getCheckoutDeliveryDate()); ?>
                        </div>
                    </div><br>
                <?php  endif; ?>
                <?php if($customFields->getCheckoutDeliveryTime()): ?>
                    <div class="box">
                        <label class="box-title"><span><?php /* @escapeNotVerified */// echo __('Delivery Time:') ?></span></label>
                        <div class="box-content">
                            <?php // echo $this->escapeHtml($customFields->getCheckoutDeliveryTime()); ?>
                        </div>
                    </div><br>
                <?php  endif; ?>
            <?php  endif; ?>
        </div>
    </div>
    <script type="text/javascript">
        require(['jquery'], function($){
            $('.admin__page-section-content.custom-magepow-bank').appendTo('.sales-order-view .order-view-billing-shipping .admin__page-section-content .admin__page-section-item.order-payment-method');
            $('.admin__page-section-content.custom-magepow-shipping-method').appendTo('.sales-order-view .order-view-billing-shipping .admin__page-section-content .admin__page-section-item.order-shipping-method');
        });
    </script>
<?php endif; ?>
<?php endif; ?>
