<?php
/**
 * @copyright Copyright © 2020 Magepow. All rights reserved.
 * @author    Magepow
 * @category Magepow
 * @copyright Copyright (c) 2014 Magepow (<https://www.magepow.com>)
 * @license <https://www.magepow.com/license-agreement.html>
 * @Author: magepow<support@magepow.com>
 * @github: <https://github.com/magepow>
 */
/** @var  Magepow\CheckoutCustomForm\Block\Order\CustomFields $block */

/** @var  Magepow\CheckoutCustomForm\Model\Data\CustomFields $customFields */
$customFields = $block->getCustomFields($block->getOrder());
?>
<?php if($customFields): ?>
    <?php if($customFields->getImeiTime() || $customFields->getCheckboxBankTranfer() || $customFields->getBankNameOnAccount() || $customFields->getBankAccountNumber() || $customFields->getBankAccountShortCode()): ?>
    <?php 
        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $orderId  = $this->getRequest()->getParam('order_id');
        $orderRepository = $objectManager->create('Magento\Sales\Api\OrderRepositoryInterface')->get($orderId);
        $checkPayment = $orderRepository->getPayment()->getData('method');
    ?>
        <div class="magepow-custom-form-bank">
            <span><?php /* @escapeNotVerified */ echo __('Billing Information') ?></span>
            <div class="box-content-customform">
               <?php if($customFields->getImeiTime()): ?>
                    <label><?php /* @escapeNotVerified */ echo __('Imei:') ?>:</label>
                    <?php echo $this->escapeHtml($customFields->getImeiTime()); ?><br>
                <?php  endif; ?>
                <?php if($checkPayment == 'checkmo'): ?>
                    <?php if($customFields->getCheckboxBankTranfer()): ?>
                        <label><?php /* @escapeNotVerified */ echo __('PayPal Email:') ?>:</label>
                        <?php echo $this->escapeHtml($customFields->getCheckboxBankTranfer()); ?><br>
                    <?php  endif; ?>
                <?php elseif($checkPayment == 'banktransfer'): ?>
                    <?php if($customFields->getBankNameOnAccount()): ?>
                        <label><?php /* @escapeNotVerified */ echo __('Name On Account:') ?>:</label>
                        <?php echo $this->escapeHtml($customFields->getBankNameOnAccount()); ?><br>
                    <?php  endif; ?>
                    <?php if($customFields->getBankAccountNumber()): ?>
                        <label><?php /* @escapeNotVerified */ echo __('Account Number:') ?>:</label>
                        <?php echo $this->escapeHtml($customFields->getBankAccountNumber()); ?><br>
                    <?php  endif; ?>
                    <?php if($customFields->getBankAccountShortCode()): ?>
                        <label><?php /* @escapeNotVerified */ echo __('Account Short Code:') ?>:</label>
                        <?php echo $this->escapeHtml($customFields->getBankAccountShortCode()); ?><br>  
                    <?php  endif; ?>
                <?php  endif; ?>
            </div>
        </div>

        <div class="magepow-custom-form-shipping-method">
            <div class="box-content-customform">
               <?php if($customFields->getCheckoutCollectionSchedule() == 'value_1'): ?>
                <div class="box">
                    <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Collection Today') ?></span></strong>
                </div><br>
            <?php elseif($customFields->getCheckoutCollectionSchedule() == 'value_2'): ?>
                <div class="box">
                    <strong class="box-title"><span><?php /* @escapeNotVerified */ echo __('Schedule for Later') ?></span></strong>
                </div><br>
                <?php if($customFields->getCheckoutDeliveryDate()): ?>
                    <div class="box">
                        <label class="box-title"><span><?php /* @escapeNotVerified */ echo __('Delivery Date:') ?></span></label>
                        <div class="box-content">
                            <?php echo $this->escapeHtml($customFields->getCheckoutDeliveryDate()); ?>
                        </div>
                    </div><br>
                <?php  endif; ?>
            <?php  endif; ?>
            </div>
            
        </div>
      
        <script type="text/javascript">
            require(['jquery'], function($) {
               $('.magepow-custom-form-bank').appendTo('.sales-order-view .block-order-details-view .box.box-order-billing-method .box-content'); 
               $('.magepow-custom-form-shipping-method').appendTo('.sales-order-view .block-order-details-view .box.box-order-shipping-method .box-content'); 
            });
        </script>
    <?php endif; ?>
<?php endif; ?>
